PROBLEMS = [
    # ─── EASY ────────────────────────────────────────────────────────────────
    {
        "id": 1,
        "title": "Homology of the Circle",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["CW complex", "spheres"],
        "statement": r"Compute the singular homology groups $H_n(S^1;\,\mathbb{Z})$ for all $n \geq 0$.",
        "hints": [
            r"Give $S^1$ a minimal CW structure: one 0-cell $v$ and one 1-cell $e$ with both endpoints attached to $v$.",
            r"The cellular chain complex is $0 \to \mathbb{Z} \xrightarrow{d_1} \mathbb{Z} \to 0$. Compute $d_1(e) = e(1) - e(0)$.",
            r"Since both endpoints of $e$ are $v$, we get $d_1(e) = v - v = 0$, so $d_1 = 0$.",
        ],
        "solution": {
            "answer": r"$H_0(S^1) \cong \mathbb{Z},\quad H_1(S^1) \cong \mathbb{Z},\quad H_n(S^1) = 0 \text{ for } n \geq 2.$",
            "steps": [
                r"Give $S^1$ the CW structure with one 0-cell $v$ and one 1-cell $e$ (a loop), so $C_1 = \mathbb{Z}\langle e\rangle$ and $C_0 = \mathbb{Z}\langle v\rangle$.",
                r"The cellular chain complex is $0 \to \mathbb{Z} \xrightarrow{d_1} \mathbb{Z} \to 0$.",
                r"Boundary map: $d_1(e) = v - v = 0$, so $d_1 = 0$. All higher boundary maps are zero (no cells in degree $\geq 2$).",
                r"$H_0 = \ker(d_0)/\operatorname{im}(d_1) = \mathbb{Z}/0 = \mathbb{Z}$ — one connected component.",
                r"$H_1 = \ker(d_1)/\operatorname{im}(d_2) = \mathbb{Z}/0 = \mathbb{Z}$ — the loop $e$ represents a free homology class.",
                r"Since $C_n = 0$ for $n \geq 2$, we have $H_n(S^1) = 0$ for $n \geq 2$.",
            ],
        },
    },
    {
        "id": 2,
        "title": "Homology of the 2-Sphere",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["CW complex", "spheres"],
        "statement": r"Compute $H_n(S^2;\,\mathbb{Z})$ for all $n \geq 0$.",
        "hints": [
            r"Use the minimal CW structure on $S^2$: one 0-cell $v$ and one 2-cell $e^2$ attached by the constant map to $v$.",
            r"There is no 1-cell, so $C_1 = 0$. What does the chain complex look like?",
            r"The attaching map $S^1 \to \{v\}$ is constant, hence has degree 0.",
        ],
        "solution": {
            "answer": r"$H_0(S^2) \cong \mathbb{Z},\quad H_2(S^2) \cong \mathbb{Z},\quad H_n(S^2) = 0 \text{ otherwise.}$",
            "steps": [
                r"CW structure: one 0-cell $v$ and one 2-cell $e^2$ (attached by the constant map $S^1 \to v$). No 1-cells.",
                r"Cellular chain complex: $0 \to \mathbb{Z} \xrightarrow{d_2} 0 \xrightarrow{d_1} \mathbb{Z} \to 0$.",
                r"All boundary maps are zero (since $C_1 = 0$ and the attaching map is degree 0).",
                r"$H_2 = \ker(d_2)/\operatorname{im}(d_3) = \mathbb{Z}/0 = \mathbb{Z}$.",
                r"$H_1 = 0/0 = 0$ (no 1-cells at all).",
                r"$H_0 = \mathbb{Z}$ (one connected component). All $H_n = 0$ for $n \geq 3$.",
            ],
        },
    },
    {
        "id": 3,
        "title": "Homology of the $n$-Sphere",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["CW complex", "spheres"],
        "statement": r"For $n \geq 1$, compute $H_k(S^n;\,\mathbb{Z})$ for all $k \geq 0$.",
        "hints": [
            r"Use the minimal CW structure on $S^n$: one 0-cell and one $n$-cell.",
            r"The attaching map of the $n$-cell is a map $S^{n-1} \to \{v\}$, which is constant.",
            r"Since there are no cells in dimensions $1, \ldots, n-1$, most boundary maps are trivially zero.",
        ],
        "solution": {
            "answer": r"$H_k(S^n) \cong \mathbb{Z}$ for $k = 0$ and $k = n$; $H_k(S^n) = 0$ otherwise.",
            "steps": [
                r"CW structure: one 0-cell $v$ and one $n$-cell $e^n$ attached by the constant map. No cells in dimensions $1, \ldots, n-1$.",
                r"Cellular chain complex: all $C_k = 0$ except $C_0 = \mathbb{Z}$ and $C_n = \mathbb{Z}$.",
                r"Boundary map $d_n: C_n \to C_{n-1}$. When $n \geq 2$, $C_{n-1} = 0$, so $d_n = 0$.",
                r"$H_n = \ker(d_n)/\operatorname{im}(d_{n+1}) = \mathbb{Z}/0 = \mathbb{Z}$.",
                r"$H_0 = \mathbb{Z}$ (connected). All other $H_k = 0$.",
                r"For $n = 1$: the unique 1-cell is a loop so $d_1 = 0$, recovering $H_0 = H_1 = \mathbb{Z}$.",
            ],
        },
    },
    {
        "id": 4,
        "title": "Homology of Contractible Spaces",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["homotopy invariance", "disk"],
        "statement": r"Show that if $X$ is contractible (e.g.\ $X = D^n$ or $X = \mathbb{R}^n$), then $H_k(X;\,\mathbb{Z}) = 0$ for $k \geq 1$ and $H_0(X) \cong \mathbb{Z}$.",
        "hints": [
            r"A contraction is a homotopy equivalence $X \simeq \{*\}$ to a point.",
            r"Homology is a homotopy invariant: if $X \simeq Y$ then $H_*(X) \cong H_*(Y)$.",
            r"Compute the homology of a single point directly from the definition.",
        ],
        "solution": {
            "answer": r"$H_0(X) \cong \mathbb{Z}$, $H_k(X) = 0$ for $k \geq 1$.",
            "steps": [
                r"By homotopy invariance, $H_*(X) \cong H_*(\{*\})$ for any contractible $X$.",
                r"For a point $\{*\}$, the singular chain complex has $C_0 = \mathbb{Z}$ (the unique 0-simplex) and $C_k = \mathbb{Z}$ for all $k$, but all boundary maps alternate between $0$ and $\text{id}$.",
                r"In fact the augmented complex $\cdots \to C_1 \to C_0 \to \mathbb{Z} \to 0$ is acyclic, giving $H_0 = \mathbb{Z}$ and $H_k = 0$ for $k \geq 1$.",
                r"For $D^n$: the radial deformation $H(x,t) = (1-t)x$ contracts $D^n$ to the origin, so $D^n$ is contractible and $H_k(D^n) = 0$ for $k \geq 1$.",
            ],
        },
    },
    {
        "id": 5,
        "title": "Homology of the Torus",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["CW complex", "surfaces", "torus"],
        "statement": r"Compute $H_n(T^2;\,\mathbb{Z})$ for the torus $T^2 = S^1 \times S^1$.",
        "hints": [
            r"Use the standard CW structure on $T^2$: one 0-cell $v$, two 1-cells $a, b$, and one 2-cell $e$ attached by the word $aba^{-1}b^{-1}$.",
            r"For the boundary map $d_1$: both $a$ and $b$ are loops at $v$, so $d_1(a) = v - v = 0$ and $d_1(b) = 0$.",
            r"For $d_2(e)$: count how many times the attaching word traverses each 1-cell, with sign. Note $a$ appears once forward and once backward.",
        ],
        "solution": {
            "answer": r"$H_0(T^2) \cong \mathbb{Z},\quad H_1(T^2) \cong \mathbb{Z}^2,\quad H_2(T^2) \cong \mathbb{Z},\quad H_n = 0 \text{ for } n \geq 3.$",
            "steps": [
                r"CW structure: one 0-cell $v$, two 1-cells $a, b$, one 2-cell $e$. Attaching word: $aba^{-1}b^{-1}$.",
                r"Chain groups: $C_2 = \mathbb{Z}\langle e\rangle$, $C_1 = \mathbb{Z}\langle a\rangle \oplus \mathbb{Z}\langle b\rangle$, $C_0 = \mathbb{Z}\langle v\rangle$.",
                r"$d_1(a) = v - v = 0$, $d_1(b) = v - v = 0$. So $d_1 = 0$.",
                r"$d_2(e)$: the 2-cell boundary traverses $a$ once forward and once backward (net $0$), and $b$ once forward and once backward (net $0$). Thus $d_2 = 0$.",
                r"$H_2 = \ker(d_2)/\operatorname{im}(d_3) = \mathbb{Z}/0 = \mathbb{Z}$.",
                r"$H_1 = \ker(d_1)/\operatorname{im}(d_2) = \mathbb{Z}^2/0 = \mathbb{Z}^2$, generated by $[a]$ and $[b]$.",
                r"$H_0 = \mathbb{Z}$. All higher groups vanish.",
            ],
        },
    },
    {
        "id": 6,
        "title": "Homology of the Real Projective Plane",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["CW complex", "projective spaces", "torsion"],
        "statement": r"Compute $H_n(\mathbb{R}P^2;\,\mathbb{Z})$ for all $n \geq 0$.",
        "hints": [
            r"Give $\mathbb{R}P^2$ a CW structure: one 0-cell $v$, one 1-cell $a$ (a loop), one 2-cell $e$ attached by the word $aa$ (i.e.\ $a^2$).",
            r"The attaching map of $e$ traverses $a$ twice in the same direction, so $d_2(e) = 2a$.",
            r"The kernel and cokernel of the map $\times 2: \mathbb{Z} \to \mathbb{Z}$ are $0$ and $\mathbb{Z}/2$.",
        ],
        "solution": {
            "answer": r"$H_0(\mathbb{R}P^2) \cong \mathbb{Z},\quad H_1(\mathbb{R}P^2) \cong \mathbb{Z}/2,\quad H_n(\mathbb{R}P^2) = 0 \text{ for } n \geq 2.$",
            "steps": [
                r"CW structure: one 0-cell $v$, one 1-cell $a$, one 2-cell $e$ attached by the degree-2 map $a^2$.",
                r"Chain complex: $0 \to \mathbb{Z} \xrightarrow{d_2} \mathbb{Z} \xrightarrow{d_1} \mathbb{Z} \to 0$.",
                r"$d_1(a) = v - v = 0$; $d_2(e) = 2\cdot a$ (the attaching map winds around the 1-skeleton twice).",
                r"$H_2 = \ker(d_2) = \ker(\times 2: \mathbb{Z} \to \mathbb{Z}) = 0$ (multiplication by 2 is injective).",
                r"$H_1 = \ker(d_1)/\operatorname{im}(d_2) = \mathbb{Z}/2\mathbb{Z} \cong \mathbb{Z}/2$.",
                r"$H_0 = \mathbb{Z}$. $\mathbb{R}P^2$ is non-orientable, consistent with $H_2 = 0$.",
            ],
        },
    },
    {
        "id": 7,
        "title": "Homology of the Klein Bottle",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["CW complex", "surfaces", "torsion"],
        "statement": r"Compute $H_n(K;\,\mathbb{Z})$ for all $n \geq 0$, where $K$ is the Klein bottle.",
        "hints": [
            r"Use the CW structure with one 0-cell $v$, two 1-cells $a, b$, and one 2-cell attached by $aba b^{-1}$.",
            r"For $d_2$: count signed occurrences of each 1-cell in the attaching word $abab^{-1}$. Cell $a$ appears twice positively; $b$ appears once positively and once negatively.",
            r"$d_2(e) = 2a + 0 \cdot b = 2a$ in $C_1 = \mathbb{Z}\langle a\rangle \oplus \mathbb{Z}\langle b\rangle$.",
        ],
        "solution": {
            "answer": r"$H_0(K) \cong \mathbb{Z},\quad H_1(K) \cong \mathbb{Z} \oplus \mathbb{Z}/2,\quad H_n(K) = 0 \text{ for } n \geq 2.$",
            "steps": [
                r"CW structure: one 0-cell $v$, two 1-cells $a, b$, one 2-cell $e$ with attaching word $abab^{-1}$.",
                r"$d_1(a) = 0$, $d_1(b) = 0$ (both are loops at $v$).",
                r"$d_2(e)$: $a$ appears at positions 1 and 3, both with positive orientation, giving coefficient $+2$. $b$ appears at position 2 (positive) and position 4 as $b^{-1}$ (negative), giving coefficient $0$. Thus $d_2(e) = 2a$.",
                r"$H_2 = \ker(d_2: \mathbb{Z} \to \mathbb{Z}\langle a\rangle \oplus \mathbb{Z}\langle b\rangle)$. The map $e \mapsto (2, 0)$ is injective, so $H_2 = 0$.",
                r"$H_1 = \mathbb{Z}^2/\langle (2,0)\rangle \cong (\mathbb{Z}/2) \oplus \mathbb{Z}$, generated by $[a]$ (2-torsion) and $[b]$ (free).",
                r"$H_0 = \mathbb{Z}$. As expected for a non-orientable surface: $H_2 = 0$.",
            ],
        },
    },
    {
        "id": 8,
        "title": "Homology of the Figure Eight",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["CW complex", "wedge sums", "graphs"],
        "statement": r"Compute $H_n(S^1 \vee S^1;\,\mathbb{Z})$ for all $n \geq 0$, where $S^1 \vee S^1$ is the wedge of two circles.",
        "hints": [
            r"The wedge $S^1 \vee S^1$ is a graph with one vertex and two edges, both loops.",
            r"The cellular chain complex is $0 \to \mathbb{Z}^2 \xrightarrow{d_1} \mathbb{Z} \to 0$.",
            r"Both edges are loops at the single vertex, so $d_1 = 0$ for both generators.",
        ],
        "solution": {
            "answer": r"$H_0(S^1 \vee S^1) \cong \mathbb{Z},\quad H_1(S^1 \vee S^1) \cong \mathbb{Z}^2,\quad H_n = 0 \text{ for } n \geq 2.$",
            "steps": [
                r"CW structure: one 0-cell $v$ (the wedge point), two 1-cells $a$ and $b$ (both loops at $v$). No higher cells.",
                r"Chain complex: $0 \to \mathbb{Z}\langle a\rangle \oplus \mathbb{Z}\langle b\rangle \xrightarrow{d_1} \mathbb{Z}\langle v\rangle \to 0$.",
                r"$d_1(a) = v - v = 0$ and $d_1(b) = v - v = 0$, so $d_1 = 0$.",
                r"$H_1 = \ker(d_1)/0 = \mathbb{Z}^2$, generated by the two independent loops $[a]$ and $[b]$.",
                r"$H_0 = \mathbb{Z}$ (connected). No 2-cells, so $H_n = 0$ for $n \geq 2$.",
                r"More generally, for a finite connected graph with $V$ vertices and $E$ edges: $H_1 \cong \mathbb{Z}^{E-V+1}$.",
            ],
        },
    },
    {
        "id": 9,
        "title": "Homology of the Möbius Band",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["deformation retract", "homotopy equivalence"],
        "statement": r"Compute $H_n(M;\,\mathbb{Z})$ for the Möbius band $M$.",
        "hints": [
            r"Show that the Möbius band deformation retracts onto its core circle.",
            r"The retraction sends each point to the corresponding point on the central circle.",
            r"Use homotopy invariance of homology.",
        ],
        "solution": {
            "answer": r"$H_0(M) \cong \mathbb{Z},\quad H_1(M) \cong \mathbb{Z},\quad H_n(M) = 0 \text{ for } n \geq 2.$",
            "steps": [
                r"The Möbius band $M$ deformation retracts onto its core circle $S^1$: the map $r: M \to S^1$ sends $(s, t) \mapsto s$ (where $s \in S^1$ is the circle coordinate and $t \in [-1,1]$ is the width), and the homotopy $H(s,t,u) = (s, (1-u)t)$ is a deformation retraction.",
                r"Since $M \simeq S^1$, homotopy invariance gives $H_*(M) \cong H_*(S^1)$.",
                r"$H_0(M) \cong \mathbb{Z}$ (connected), $H_1(M) \cong \mathbb{Z}$ (generated by the core circle), $H_n = 0$ for $n \geq 2$.",
                r"Note: despite appearing 'two-dimensional', the Möbius band has the homology of a circle, not a surface — its boundary $\partial M \cong S^1$ wraps around twice.",
            ],
        },
    },
    {
        "id": 10,
        "title": "Are $S^1$ and $S^2$ Homeomorphic?",
        "type": "homeomorphism",
        "difficulty": "easy",
        "tags": ["homeomorphism invariants", "spheres"],
        "statement": r"Determine whether $S^1$ and $S^2$ are homeomorphic. Justify your answer using a topological invariant.",
        "hints": [
            r"A homeomorphism induces isomorphisms on all homology groups.",
            r"Compare $H_1(S^1)$ and $H_1(S^2)$.",
        ],
        "solution": {
            "answer": r"No, $S^1$ and $S^2$ are not homeomorphic.",
            "steps": [
                r"Suppose for contradiction there exists a homeomorphism $f: S^1 \to S^2$. Then $f_*: H_n(S^1) \xrightarrow{\cong} H_n(S^2)$ for all $n$.",
                r"But $H_1(S^1) \cong \mathbb{Z}$ while $H_1(S^2) = 0$. These groups are not isomorphic.",
                r"Contradiction. Hence $S^1 \not\cong S^2$.",
                r"Intuitively: any loop in $S^2$ can be contracted to a point (since $S^2$ is simply connected), but the fundamental loop in $S^1$ cannot be contracted.",
            ],
        },
    },
    {
        "id": 11,
        "title": "Are the Torus and Klein Bottle Homeomorphic?",
        "type": "homeomorphism",
        "difficulty": "easy",
        "tags": ["homeomorphism invariants", "surfaces", "orientability"],
        "statement": r"Determine whether the torus $T^2$ and the Klein bottle $K$ are homeomorphic.",
        "hints": [
            r"Compare $H_2(T^2)$ and $H_2(K)$.",
            r"A closed connected orientable $n$-manifold has $H_n \cong \mathbb{Z}$.",
        ],
        "solution": {
            "answer": r"No, $T^2$ and $K$ are not homeomorphic.",
            "steps": [
                r"$H_2(T^2) \cong \mathbb{Z}$ and $H_2(K) = 0$: these groups differ.",
                r"Since a homeomorphism would induce an isomorphism on $H_2$, no homeomorphism can exist.",
                r"The underlying reason is orientability: $T^2$ is orientable (it has a well-defined global 2-cycle), while $K$ is non-orientable.",
                r"Another invariant: $H_1(T^2) \cong \mathbb{Z}^2$ (torsion-free) whereas $H_1(K) \cong \mathbb{Z} \oplus \mathbb{Z}/2$ (has torsion).",
            ],
        },
    },
    {
        "id": 12,
        "title": "Homology of Orientable Surfaces",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["surfaces", "CW complex", "genus"],
        "statement": r"Compute $H_n(\Sigma_g;\,\mathbb{Z})$ for the closed orientable surface of genus $g$ ($g \geq 0$).",
        "hints": [
            r"For genus $g$, the standard polygon model gives a CW structure: one 0-cell, $2g$ 1-cells, one 2-cell.",
            r"The attaching word is $a_1 b_1 a_1^{-1} b_1^{-1} \cdots a_g b_g a_g^{-1} b_g^{-1}$. Check that $d_2 = 0$.",
        ],
        "solution": {
            "answer": r"$H_0(\Sigma_g) \cong \mathbb{Z},\quad H_1(\Sigma_g) \cong \mathbb{Z}^{2g},\quad H_2(\Sigma_g) \cong \mathbb{Z},\quad H_n = 0 \text{ for } n \geq 3.$",
            "steps": [
                r"CW structure: one 0-cell $v$, generators $a_1, b_1, \ldots, a_g, b_g$ (each a loop at $v$), and one 2-cell attached by $a_1 b_1 a_1^{-1} b_1^{-1} \cdots a_g b_g a_g^{-1} b_g^{-1}$.",
                r"$d_1 = 0$: all 1-cells are loops at $v$.",
                r"$d_2(e) = 0$: each $a_i$ (resp.\ $b_i$) appears once with $+$ sign and once with $-$ sign in the word, giving net coefficient 0.",
                r"$H_2 = \mathbb{Z}$ (generated by the fundamental class $[e]$).",
                r"$H_1 = \mathbb{Z}^{2g}$, freely generated by $[a_1], [b_1], \ldots, [a_g], [b_g]$.",
                r"For $g = 0$: $\Sigma_0 = S^2$, giving $H_1 = 0$ and $H_2 = \mathbb{Z}$. ✓",
            ],
        },
    },
    {
        "id": 13,
        "title": "Homology of $S^1 \\vee S^2$",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["wedge sums", "reduced homology"],
        "statement": r"Compute $H_n(S^1 \vee S^2;\,\mathbb{Z})$ for all $n \geq 0$.",
        "hints": [
            r"For a wedge sum $X \vee Y$, the reduced homology satisfies $\tilde{H}_n(X \vee Y) \cong \tilde{H}_n(X) \oplus \tilde{H}_n(Y)$.",
            r"Compute $\tilde{H}_*(S^1)$ and $\tilde{H}_*(S^2)$ and add them.",
        ],
        "solution": {
            "answer": r"$H_0 \cong \mathbb{Z},\quad H_1 \cong \mathbb{Z},\quad H_2 \cong \mathbb{Z},\quad H_n = 0 \text{ for } n \geq 3.$",
            "steps": [
                r"For any spaces $X, Y$ with a common basepoint, $\tilde{H}_n(X \vee Y) \cong \tilde{H}_n(X) \oplus \tilde{H}_n(Y)$.",
                r"$\tilde{H}_*(S^1)$: $\tilde{H}_1 = \mathbb{Z}$, all other reduced groups $= 0$.",
                r"$\tilde{H}_*(S^2)$: $\tilde{H}_2 = \mathbb{Z}$, all other reduced groups $= 0$.",
                r"Adding: $\tilde{H}_1(S^1 \vee S^2) = \mathbb{Z}$ (from $S^1$) and $\tilde{H}_2(S^1 \vee S^2) = \mathbb{Z}$ (from $S^2$).",
                r"Restoring $H_0 = \tilde{H}_0 \oplus \mathbb{Z} = \mathbb{Z}$. All higher groups vanish.",
            ],
        },
    },
    {
        "id": 14,
        "title": "Homology of $\\mathbb{R}P^1$",
        "type": "homology",
        "difficulty": "easy",
        "tags": ["projective spaces", "homeomorphism"],
        "statement": r"Identify $\mathbb{R}P^1$ as a familiar space and compute its homology $H_n(\mathbb{R}P^1;\,\mathbb{Z})$.",
        "hints": [
            r"$\mathbb{R}P^1$ is the space of lines through the origin in $\mathbb{R}^2$, which is parameterized by angles $\theta \in [0, \pi]$ with $0 \sim \pi$.",
            r"What well-known space is this homeomorphic to?",
        ],
        "solution": {
            "answer": r"$\mathbb{R}P^1 \cong S^1$, so $H_0 \cong \mathbb{Z}$, $H_1 \cong \mathbb{Z}$, and $H_n = 0$ for $n \geq 2$.",
            "steps": [
                r"$\mathbb{R}P^1$ is the quotient $S^1/\{\pm 1\}$, identifying antipodal points on the circle.",
                r"The map $\theta \mapsto 2\theta$ sends $[0, \pi]/(0\sim\pi)$ homeomorphically to $S^1$. Hence $\mathbb{R}P^1 \cong S^1$.",
                r"Alternatively, the double cover $S^1 \to \mathbb{R}P^1$ exhibits $\mathbb{R}P^1$ as the base of a 2-sheeted covering, but the total space $S^1$ and the base $\mathbb{R}P^1$ are both homeomorphic to $S^1$.",
                r"Homology: $H_0 = H_1 = \mathbb{Z}$, $H_n = 0$ for $n \geq 2$.",
                r"Contrast with $\mathbb{R}P^2$, where the identification creates torsion in $H_1$. The extra dimension in $\mathbb{R}P^2$ is responsible.",
            ],
        },
    },
    # ─── MEDIUM ──────────────────────────────────────────────────────────────
    {
        "id": 15,
        "title": "Homology of $\\mathbb{R}P^3$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["CW complex", "projective spaces", "torsion"],
        "statement": r"Compute $H_n(\mathbb{R}P^3;\,\mathbb{Z})$ for all $n \geq 0$.",
        "hints": [
            r"$\mathbb{R}P^3$ has a CW structure with one cell in each dimension $0, 1, 2, 3$.",
            r"The cellular boundary map satisfies $d_k = 1 + (-1)^k$, so $d_k = 2$ for $k$ even and $d_k = 0$ for $k$ odd.",
            r"Write out the chain complex $0 \to \mathbb{Z} \xrightarrow{0} \mathbb{Z} \xrightarrow{2} \mathbb{Z} \xrightarrow{0} \mathbb{Z} \to 0$ and compute homology.",
        ],
        "solution": {
            "answer": r"$H_0 \cong \mathbb{Z},\quad H_1 \cong \mathbb{Z}/2,\quad H_2 = 0,\quad H_3 \cong \mathbb{Z},\quad H_n = 0 \text{ for } n \geq 4.$",
            "steps": [
                r"For $\mathbb{R}P^n$, the CW structure has one cell $e^k$ in each dimension $0 \leq k \leq n$. The boundary map is $d_k = \deg(\text{attaching map}) = 1 + (-1)^k$.",
                r"For $n = 3$: chain complex $0 \to C_3 \xrightarrow{d_3=0} C_2 \xrightarrow{d_2=2} C_1 \xrightarrow{d_1=0} C_0 \to 0$ with each $C_k = \mathbb{Z}$.",
                r"$H_3 = \ker(d_3)/\operatorname{im}(d_4) = \ker(0)/0 = \mathbb{Z}$.",
                r"$H_2 = \ker(d_2)/\operatorname{im}(d_3) = \ker(\times 2)/\operatorname{im}(0) = 0/0 = 0$.",
                r"$H_1 = \ker(d_1)/\operatorname{im}(d_2) = \mathbb{Z}/2\mathbb{Z} = \mathbb{Z}/2$.",
                r"$H_0 = \mathbb{Z}$. Note $\mathbb{R}P^3$ is a closed orientable 3-manifold (it is the group $SO(3)$), consistent with $H_3 = \mathbb{Z}$.",
            ],
        },
    },
    {
        "id": 16,
        "title": "Homology of $\\mathbb{R}P^n$ (General Formula)",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["CW complex", "projective spaces", "torsion"],
        "statement": r"Compute $H_k(\mathbb{R}P^n;\,\mathbb{Z})$ for all $k \geq 0$ and all $n \geq 1$.",
        "hints": [
            r"The CW structure on $\mathbb{R}P^n$ has one cell in each dimension $0, 1, \ldots, n$.",
            r"The cellular boundary map is $d_k = 1 + (-1)^k$: equal to $2$ for $k$ even, $0$ for $k$ odd.",
            r"Compute $\ker$ and $\operatorname{im}$ carefully, paying attention to whether $n$ is even or odd.",
        ],
        "solution": {
            "answer": r"$H_k(\mathbb{R}P^n;\mathbb{Z}) = \begin{cases} \mathbb{Z} & k=0 \\ \mathbb{Z}/2 & k \text{ odd},\; 0 < k < n \\ \mathbb{Z} & k = n,\; n \text{ odd} \\ 0 & \text{otherwise} \end{cases}$",
            "steps": [
                r"CW structure: $C_k = \mathbb{Z}$ for $0 \leq k \leq n$, $0$ otherwise. Boundary map: $d_k = \times(1+(-1)^k)$, i.e.\ $d_k = \times 2$ for $k$ even, $d_k = 0$ for $k$ odd.",
                r"For $0 < k < n$ with $k$ odd: $d_k = 0$ and $d_{k+1} = \times 2$. So $H_k = \ker(0)/\operatorname{im}(\times 2) = \mathbb{Z}/2\mathbb{Z}$.",
                r"For $0 < k < n$ with $k$ even: $d_k = \times 2$ and $d_{k+1} = 0$. So $H_k = \ker(\times 2)/\operatorname{im}(0) = 0/0 = 0$.",
                r"Top dimension $k = n$: if $n$ is odd, $d_n = 0$ and there is no $d_{n+1}$, giving $H_n = \mathbb{Z}$. If $n$ is even, $d_n = \times 2$ and $H_n = \ker(\times 2) = 0$.",
                r"$H_0 = \mathbb{Z}$ (connected). Examples: $\mathbb{R}P^2$: $(H_0, H_1, H_2) = (\mathbb{Z}, \mathbb{Z}/2, 0)$; $\mathbb{R}P^4$: $(\mathbb{Z}, \mathbb{Z}/2, 0, \mathbb{Z}/2, 0)$.",
            ],
        },
    },
    {
        "id": 17,
        "title": "Homology of $\\mathbb{C}P^n$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["CW complex", "projective spaces", "complex"],
        "statement": r"Compute $H_k(\mathbb{C}P^n;\,\mathbb{Z})$ for all $k \geq 0$.",
        "hints": [
            r"$\mathbb{C}P^n$ has a CW structure with exactly one cell in each even dimension $0, 2, 4, \ldots, 2n$. There are no odd-dimensional cells.",
            r"When there are no cells in consecutive dimensions, what can you say about the boundary maps?",
        ],
        "solution": {
            "answer": r"$H_k(\mathbb{C}P^n;\mathbb{Z}) \cong \mathbb{Z}$ for $k = 0, 2, 4, \ldots, 2n$, and $H_k = 0$ for all odd $k$ and for $k > 2n$.",
            "steps": [
                r"$\mathbb{C}P^n$ is built by $\mathbb{C}P^k = \mathbb{C}P^{k-1} \cup e^{2k}$, giving a CW structure with cells only in even dimensions $0, 2, 4, \ldots, 2n$.",
                r"The cellular chain complex has $C_{2k} = \mathbb{Z}$ for $0 \leq k \leq n$ and $C_{\text{odd}} = 0$.",
                r"Every boundary map $d_k: C_k \to C_{k-1}$ has $C_{k-1} = 0$ (since no odd cells) or $C_k = 0$, forcing $d_k = 0$.",
                r"Hence every chain is a cycle and every cycle is not a boundary: $H_{2k} = \mathbb{Z}$ for $0 \leq k \leq n$.",
                r"$H_{\text{odd}} = 0$ since $C_{\text{odd}} = 0$. $H_k = 0$ for $k > 2n$.",
                r"This is much simpler than $\mathbb{R}P^n$: no boundary map ever contributes torsion.",
            ],
        },
    },
    {
        "id": 18,
        "title": "Künneth Formula: $H_*(S^m \\times S^n)$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["Künneth formula", "product spaces", "spheres"],
        "statement": r"Using the Künneth formula, compute $H_k(S^m \times S^n;\,\mathbb{Z})$ for $m, n \geq 1$ and all $k \geq 0$. Treat the cases $m \neq n$ and $m = n$ separately.",
        "hints": [
            r"The Künneth formula states: $H_k(X \times Y) \cong \bigoplus_{p+q=k} H_p(X) \otimes H_q(Y) \;\oplus\; \bigoplus_{p+q=k-1} \operatorname{Tor}(H_p(X), H_q(Y))$.",
            r"Both $H_*(S^m)$ and $H_*(S^n)$ are torsion-free, so all $\operatorname{Tor}$ terms vanish.",
            r"$H_*(S^m) = \mathbb{Z}$ in degrees $0$ and $m$, zero elsewhere.",
        ],
        "solution": {
            "answer": r"For $m \neq n$: $H_k = \mathbb{Z}$ for $k \in \{0, m, n, m+n\}$ and $0$ otherwise. For $m = n$: $H_0 = H_{2m} = \mathbb{Z}$ and $H_m = \mathbb{Z}^2$.",
            "steps": [
                r"Since $H_*(S^m)$ is torsion-free, the $\operatorname{Tor}$ terms all vanish and $H_k(S^m \times S^n) = \bigoplus_{p+q=k} H_p(S^m) \otimes H_q(S^n)$.",
                r"Non-zero terms in $H_*(S^m)$: at degrees $0$ and $m$. Non-zero terms in $H_*(S^n)$: at degrees $0$ and $n$.",
                r"Products contributing to $H_k$: $(p,q) \in \{(0,0), (m,0), (0,n), (m,n)\}$ give non-zero contributions at $k = 0, m, n, m+n$.",
                r"Case $m \neq n$: these four degrees are distinct, each contributing $\mathbb{Z} \otimes \mathbb{Z} = \mathbb{Z}$. So $H_0 = H_m = H_n = H_{m+n} = \mathbb{Z}$.",
                r"Case $m = n$: degrees $m$ and $n$ coincide, giving $H_m = \mathbb{Z}^2$ (from $(m,0)$ and $(0,n)$).",
                r"Example: $H_*(S^1 \times S^2) = (\mathbb{Z}, \mathbb{Z}, \mathbb{Z}, \mathbb{Z}, 0, \ldots)$ in degrees $0,1,2,3$.",
            ],
        },
    },
    {
        "id": 19,
        "title": "Homology of the 3-Torus $T^3$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["Künneth formula", "product spaces", "torus"],
        "statement": r"Compute $H_n(T^3;\,\mathbb{Z})$ for $T^3 = S^1 \times S^1 \times S^1$.",
        "hints": [
            r"Apply the Künneth formula iteratively: first compute $H_*(T^2)$, then $H_*(T^2 \times S^1)$.",
            r"Alternatively, use the general formula: $H_k(T^n) \cong \mathbb{Z}^{\binom{n}{k}}$.",
        ],
        "solution": {
            "answer": r"$H_0 \cong \mathbb{Z},\quad H_1 \cong \mathbb{Z}^3,\quad H_2 \cong \mathbb{Z}^3,\quad H_3 \cong \mathbb{Z},\quad H_n = 0 \text{ for } n \geq 4.$",
            "steps": [
                r"We know $H_*(T^2) = (\mathbb{Z}, \mathbb{Z}^2, \mathbb{Z}, 0, \ldots)$. Apply Künneth to $T^3 = T^2 \times S^1$.",
                r"Since all homology groups are free, Tor terms vanish: $H_k(T^3) = \bigoplus_{p+q=k} H_p(T^2) \otimes H_q(S^1)$.",
                r"$H_q(S^1) = \mathbb{Z}$ for $q = 0, 1$ and $0$ otherwise. So: $H_k(T^3) = H_k(T^2) \oplus H_{k-1}(T^2)$.",
                r"$H_0 = \mathbb{Z} \oplus 0 = \mathbb{Z}$, $H_1 = \mathbb{Z}^2 \oplus \mathbb{Z} = \mathbb{Z}^3$, $H_2 = \mathbb{Z} \oplus \mathbb{Z}^2 = \mathbb{Z}^3$, $H_3 = 0 \oplus \mathbb{Z} = \mathbb{Z}$.",
                r"General formula: $H_k(T^n) \cong \mathbb{Z}^{\binom{n}{k}}$ (exterior algebra basis), confirming $\binom{3}{0}=1, \binom{3}{1}=3, \binom{3}{2}=3, \binom{3}{3}=1$.",
            ],
        },
    },
    {
        "id": 20,
        "title": "Künneth Formula: $H_*(S^1 \\times \\mathbb{R}P^2)$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["Künneth formula", "torsion", "projective spaces"],
        "statement": r"Compute $H_n(S^1 \times \mathbb{R}P^2;\,\mathbb{Z})$ using the Künneth formula.",
        "hints": [
            r"Recall $H_*(S^1) = (\mathbb{Z}, \mathbb{Z}, 0, \ldots)$ and $H_*(\mathbb{R}P^2) = (\mathbb{Z}, \mathbb{Z}/2, 0, \ldots)$.",
            r"Since $\mathbb{R}P^2$ has torsion, the $\operatorname{Tor}$ term is non-trivial. Recall $\operatorname{Tor}(\mathbb{Z}/m, \mathbb{Z}/n) \cong \mathbb{Z}/\gcd(m,n)$ and $\operatorname{Tor}(\mathbb{Z}, A) = 0$.",
            r"Organize contributions to each degree $n$ by listing all pairs $(p,q)$ with $p + q = n$ and $p + q = n-1$.",
        ],
        "solution": {
            "answer": r"$H_0 \cong \mathbb{Z},\quad H_1 \cong \mathbb{Z} \oplus \mathbb{Z}/2,\quad H_2 \cong \mathbb{Z}/2,\quad H_n = 0 \text{ for } n \geq 3.$",
            "steps": [
                r"Künneth: $H_k(X \times Y) \cong \bigoplus_{p+q=k} H_p(X) \otimes H_q(Y) \;\oplus\; \bigoplus_{p+q=k-1} \operatorname{Tor}(H_p(X), H_q(Y))$.",
                r"$H_0$: $H_0(S^1) \otimes H_0(\mathbb{R}P^2) = \mathbb{Z} \otimes \mathbb{Z} = \mathbb{Z}$. No Tor from degree $-1$. So $H_0 = \mathbb{Z}$.",
                r"$H_1$: Tensor part: $H_0 \otimes H_1 \oplus H_1 \otimes H_0 = \mathbb{Z}\otimes\mathbb{Z}/2 \oplus \mathbb{Z}\otimes\mathbb{Z} = \mathbb{Z}/2 \oplus \mathbb{Z}$. Tor part (from degree 0 pairs): $\operatorname{Tor}(\mathbb{Z}, \mathbb{Z}) = 0$. So $H_1 = \mathbb{Z} \oplus \mathbb{Z}/2$.",
                r"$H_2$: Tensor part: $H_0 \otimes H_2 \oplus H_1 \otimes H_1 = \mathbb{Z}\otimes 0 \oplus \mathbb{Z}\otimes\mathbb{Z}/2 = 0 \oplus \mathbb{Z}/2$. Tor part: $\operatorname{Tor}(H_0(S^1), H_1(\mathbb{R}P^2)) = \operatorname{Tor}(\mathbb{Z}, \mathbb{Z}/2) = 0$. So $H_2 = \mathbb{Z}/2$.",
                r"$H_3$: all tensor products vanish; Tor: $\operatorname{Tor}(H_1(S^1), H_1(\mathbb{R}P^2)) = \operatorname{Tor}(\mathbb{Z}, \mathbb{Z}/2) = 0$. So $H_3 = 0$.",
            ],
        },
    },
    {
        "id": 21,
        "title": "Homology of Non-Orientable Surfaces",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["CW complex", "surfaces", "torsion", "non-orientable"],
        "statement": r"Let $N_k$ denote the closed non-orientable surface obtained by taking a sphere and attaching $k$ crosscaps ($k \geq 1$). Compute $H_n(N_k;\,\mathbb{Z})$.",
        "hints": [
            r"$N_1 = \mathbb{R}P^2$, $N_2 = $ Klein bottle. CW structure: one 0-cell, $k$ 1-cells $a_1, \ldots, a_k$, one 2-cell with attaching word $a_1^2 a_2^2 \cdots a_k^2$.",
            r"$d_2(e) = 2a_1 + 2a_2 + \cdots + 2a_k$ in $C_1 = \mathbb{Z}^k$. Apply Smith normal form: this is the vector $(2, 2, \ldots, 2)$.",
            r"Change basis in $\mathbb{Z}^k$: let $f_i = a_i - a_{i+1}$ for $i < k$ and $f_k = a_1 + \cdots + a_k$. Then $d_2(e) = 2f_k$.",
        ],
        "solution": {
            "answer": r"$H_0(N_k) \cong \mathbb{Z},\quad H_1(N_k) \cong \mathbb{Z}^{k-1} \oplus \mathbb{Z}/2,\quad H_2(N_k) = 0,\quad H_n = 0 \text{ for } n \geq 3.$",
            "steps": [
                r"CW structure: one 0-cell $v$, $k$ 1-cells $a_1, \ldots, a_k$ (all loops at $v$), one 2-cell $e$ with word $a_1^2 \cdots a_k^2$.",
                r"$d_1 = 0$ (all generators are loops). $d_2(e) = (2, 2, \ldots, 2) \in \mathbb{Z}^k$.",
                r"$H_2 = \ker(d_2: \mathbb{Z} \to \mathbb{Z}^k)$. Since $e \mapsto (2,\ldots,2) \neq 0$, $d_2$ is injective, so $H_2 = 0$.",
                r"$H_1 = \mathbb{Z}^k / \langle (2,2,\ldots,2) \rangle$. Change basis: $f_i = a_i - a_{i+1}$ ($i=1,\ldots,k{-}1$) and $f_k = \sum a_i$. Then $d_2(e) = 2f_k$.",
                r"In the new basis: $H_1 = \mathbb{Z}^{k-1} \oplus (\mathbb{Z}/2)$, generated by $f_1, \ldots, f_{k-1}$ freely and $f_k$ with $2f_k = 0$.",
                r"Checks: $k=1$ ($\mathbb{R}P^2$): $H_1 = \mathbb{Z}/2$. ✓ $\quad k=2$ (Klein bottle): $H_1 = \mathbb{Z} \oplus \mathbb{Z}/2$. ✓",
            ],
        },
    },
    {
        "id": 22,
        "title": "Relative Homology $H_*(D^n, S^{n-1})$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["relative homology", "long exact sequence", "excision"],
        "statement": r"Compute $H_k(D^n, S^{n-1};\,\mathbb{Z})$ for all $k \geq 0$ and $n \geq 1$.",
        "hints": [
            r"Use the long exact sequence of the pair $(D^n, S^{n-1})$.",
            r"$D^n$ is contractible: $H_k(D^n) = \mathbb{Z}$ for $k=0$, $0$ for $k \geq 1$.",
            r"The connecting homomorphism $\partial: H_k(D^n, S^{n-1}) \to H_{k-1}(S^{n-1})$ is an isomorphism for appropriate $k$.",
        ],
        "solution": {
            "answer": r"$H_n(D^n, S^{n-1}) \cong \mathbb{Z}$, and $H_k(D^n, S^{n-1}) = 0$ for $k \neq n$.",
            "steps": [
                r"Long exact sequence: $\cdots \to H_k(S^{n-1}) \to H_k(D^n) \to H_k(D^n, S^{n-1}) \xrightarrow{\partial} H_{k-1}(S^{n-1}) \to \cdots$",
                r"Since $D^n$ is contractible: $H_k(D^n) = 0$ for $k \geq 1$ and $H_0(D^n) = \mathbb{Z}$.",
                r"For $k \geq 2$: $0 \to H_k(D^n, S^{n-1}) \xrightarrow{\cong} H_{k-1}(S^{n-1}) \to 0$. So $H_k(D^n, S^{n-1}) \cong H_{k-1}(S^{n-1})$.",
                r"$H_{k-1}(S^{n-1}) = \mathbb{Z}$ for $k-1 \in \{0, n-1\}$, i.e.\ $k = 1$ (but $H_1(D^n, S^{n-1})$ needs care) or $k = n$.",
                r"At $k = n$: $H_n(D^n, S^{n-1}) \cong H_{n-1}(S^{n-1}) = \mathbb{Z}$. All other groups vanish.",
                r"Alternatively: by excision, $H_*(D^n, S^{n-1}) \cong \tilde{H}_*(D^n/S^{n-1}) = \tilde{H}_*(S^n)$, giving $\mathbb{Z}$ in degree $n$.",
            ],
        },
    },
    {
        "id": 23,
        "title": "Mayer–Vietoris: Homology of $S^n$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["Mayer-Vietoris", "induction", "spheres"],
        "statement": r"Use the Mayer–Vietoris sequence to compute $H_k(S^n;\,\mathbb{Z})$ for all $k$ and all $n \geq 1$.",
        "hints": [
            r"Decompose $S^n = U \cup V$ where $U = S^n \setminus \{N\}$ and $V = S^n \setminus \{S\}$ (removing the north and south poles).",
            r"Both $U$ and $V$ are contractible (homeomorphic to $\mathbb{R}^n$). Their intersection $U \cap V \simeq S^{n-1}$.",
            r"Write down the Mayer–Vietoris sequence and use the fact that $H_k(U) = H_k(V) = 0$ for $k \geq 1$.",
        ],
        "solution": {
            "answer": r"$H_k(S^n) \cong \mathbb{Z}$ for $k = 0$ and $k = n$, zero otherwise (confirmed by induction).",
            "steps": [
                r"Let $U = S^n \setminus \{N\} \cong \mathbb{R}^n$ and $V = S^n \setminus \{S\} \cong \mathbb{R}^n$. Then $U \cap V \simeq S^{n-1}$.",
                r"Mayer–Vietoris: $\cdots \to H_k(U \cap V) \to H_k(U) \oplus H_k(V) \to H_k(S^n) \xrightarrow{\partial} H_{k-1}(U \cap V) \to \cdots$",
                r"Since $U, V$ are contractible, $H_k(U) = H_k(V) = 0$ for $k \geq 1$. The sequence for $k \geq 2$ reduces to $0 \to H_k(S^n) \xrightarrow{\cong} H_{k-1}(S^{n-1}) \to 0$.",
                r"So $H_k(S^n) \cong H_{k-1}(S^{n-1})$ for $k \geq 2$. By induction (base case $S^1$: $H_1(S^1) = \mathbb{Z}$), $H_n(S^n) = \mathbb{Z}$.",
                r"For $k = 1$: $0 \to H_1(S^n) \to H_0(S^{n-1}) \to H_0(U) \oplus H_0(V) \to \cdots$ With $n \geq 2$, $H_0(S^{n-1}) \to \mathbb{Z} \oplus \mathbb{Z}$ is injective, giving $H_1(S^n) = 0$.",
            ],
        },
    },
    {
        "id": 24,
        "title": "Are $\\mathbb{R}P^2$ and $T^2$ Homeomorphic?",
        "type": "homeomorphism",
        "difficulty": "medium",
        "tags": ["homeomorphism invariants", "surfaces", "torsion"],
        "statement": r"Determine whether $\mathbb{R}P^2$ and $T^2$ are homeomorphic, giving a complete invariant-based argument.",
        "hints": [
            r"Compare $H_1(\mathbb{R}P^2)$ and $H_1(T^2)$.",
            r"Also compare $H_2$ of each space.",
        ],
        "solution": {
            "answer": r"No, $\mathbb{R}P^2$ and $T^2$ are not homeomorphic.",
            "steps": [
                r"$H_1(\mathbb{R}P^2) \cong \mathbb{Z}/2$ (finite group), while $H_1(T^2) \cong \mathbb{Z}^2$ (free abelian of rank 2).",
                r"These groups are not isomorphic: $\mathbb{Z}/2$ has order 2, whereas $\mathbb{Z}^2$ is infinite.",
                r"A homeomorphism would induce an isomorphism on $H_1$, which is impossible here.",
                r"Additional invariant: $H_2(\mathbb{R}P^2) = 0$ (non-orientable) vs.\ $H_2(T^2) = \mathbb{Z}$ (orientable).",
                r"In fact $\mathbb{R}P^2$ and $T^2$ have different genus, different Euler characteristics ($\chi(\mathbb{R}P^2) = 1$, $\chi(T^2) = 0$), and different orientability.",
            ],
        },
    },
    {
        "id": 25,
        "title": "Homology of $SO(3)$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["Lie groups", "projective spaces", "homeomorphism"],
        "statement": r"Compute $H_n(SO(3);\,\mathbb{Z})$ for all $n \geq 0$, using the fact that $SO(3) \cong \mathbb{R}P^3$ as topological spaces.",
        "hints": [
            r"Every rotation in $\mathbb{R}^3$ is determined by an oriented axis (a point in $S^2$) and an angle $\theta \in [0, \pi]$.",
            r"Rotations by angle $\pi$ about antipodal axes are identical. This identifies antipodal points on the boundary hemisphere $S^2 \times \{\pi\}$.",
            r"The resulting quotient of the closed ball $B^3$ by antipodal boundary identification is $\mathbb{R}P^3$.",
        ],
        "solution": {
            "answer": r"$H_0(SO(3)) \cong \mathbb{Z},\quad H_1(SO(3)) \cong \mathbb{Z}/2,\quad H_2(SO(3)) = 0,\quad H_3(SO(3)) \cong \mathbb{Z}.$",
            "steps": [
                r"Represent a rotation by $(\mathbf{u}, \theta)$ with $\mathbf{u} \in S^2$ the axis and $\theta \in [0,\pi]$ the angle. The identity corresponds to any $(\mathbf{u}, 0)$; a $\pi$-rotation about $\mathbf{u}$ equals that about $-\mathbf{u}$.",
                r"This gives a homeomorphism $SO(3) \cong D^3 / (x \sim -x \text{ on } \partial D^3) = \mathbb{R}P^3$.",
                r"By the homeomorphism: $H_*(SO(3)) \cong H_*(\mathbb{R}P^3) = (\mathbb{Z}, \mathbb{Z}/2, 0, \mathbb{Z}, 0, \ldots)$.",
                r"The $\mathbb{Z}/2$ in $H_1$ captures the fact that $\pi_1(SO(3)) = \mathbb{Z}/2$: a $2\pi$ rotation is contractible but a $4\pi$ rotation is not.",
                r"The double cover $SU(2) \cong S^3 \to SO(3)$ confirms this: $S^3$ is simply connected and covers $SO(3)$ with fibre $\mathbb{Z}/2$.",
            ],
        },
    },
    {
        "id": 26,
        "title": "Homology of $\\mathbb{R}P^4$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["CW complex", "projective spaces", "torsion"],
        "statement": r"Compute $H_k(\mathbb{R}P^4;\,\mathbb{Z})$ for all $k \geq 0$.",
        "hints": [
            r"Apply the general formula from the $\mathbb{R}P^n$ problem with $n = 4$ (even).",
            r"The boundary maps are: $d_1 = 0$, $d_2 = \times 2$, $d_3 = 0$, $d_4 = \times 2$.",
        ],
        "solution": {
            "answer": r"$H_0 \cong \mathbb{Z},\quad H_1 \cong \mathbb{Z}/2,\quad H_2 = 0,\quad H_3 \cong \mathbb{Z}/2,\quad H_4 = 0,\quad H_n = 0 \text{ for } n \geq 5.$",
            "steps": [
                r"Chain complex for $\mathbb{R}P^4$: $0 \to C_4 \xrightarrow{\times 2} C_3 \xrightarrow{0} C_2 \xrightarrow{\times 2} C_1 \xrightarrow{0} C_0 \to 0$, each $C_k = \mathbb{Z}$.",
                r"$H_4 = \ker(\times 2)/0 = 0$ (multiplication by 2 is injective).",
                r"$H_3 = \ker(0)/\operatorname{im}(\times 2) = \mathbb{Z}/2\mathbb{Z}$.",
                r"$H_2 = \ker(\times 2)/\operatorname{im}(0) = 0$.",
                r"$H_1 = \ker(0)/\operatorname{im}(\times 2) = \mathbb{Z}/2$.",
                r"$H_0 = \mathbb{Z}$. Note: since $4$ is even, $\mathbb{R}P^4$ is non-orientable ($H_4 = 0$), unlike $\mathbb{R}P^3$.",
            ],
        },
    },
    {
        "id": 27,
        "title": "Homology of $\\mathbb{C}P^2$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["CW complex", "projective spaces", "4-manifolds"],
        "statement": r"Compute $H_k(\mathbb{C}P^2;\,\mathbb{Z})$ for all $k \geq 0$.",
        "hints": [
            r"$\mathbb{C}P^2$ is a special case of $\mathbb{C}P^n$ with $n = 2$.",
            r"CW structure: cells in real dimensions $0, 2, 4$ only.",
        ],
        "solution": {
            "answer": r"$H_0 \cong \mathbb{Z},\quad H_2 \cong \mathbb{Z},\quad H_4 \cong \mathbb{Z},\quad H_k = 0 \text{ for } k \text{ odd or } k \geq 5.$",
            "steps": [
                r"$\mathbb{C}P^2$ is a compact 4-dimensional manifold with CW structure: one 0-cell, one 2-cell, one 4-cell.",
                r"Chain complex: $0 \to C_4 \xrightarrow{d_4} C_2 \xrightarrow{d_2} C_0 \to 0$, all other $C_k = 0$.",
                r"There are no adjacent cells (e.g.\ no 3-cells or 1-cells), so all boundary maps are trivially zero.",
                r"$H_0 = H_2 = H_4 = \mathbb{Z}$; all odd-dimensional homology and $H_k$ for $k \geq 5$ vanish.",
                r"$\mathbb{C}P^2$ is a closed orientable 4-manifold: consistent with $H_4 = \mathbb{Z}$.",
                r"Euler characteristic: $\chi(\mathbb{C}P^2) = 1 - 0 + 1 - 0 + 1 = 3$.",
            ],
        },
    },
    {
        "id": 28,
        "title": "Mapping Torus of the Antipodal Map on $S^1$",
        "type": "homology",
        "difficulty": "medium",
        "tags": ["mapping torus", "fibrations", "Klein bottle"],
        "statement": r"Let $f: S^1 \to S^1$ be the reflection $f(e^{i\theta}) = e^{-i\theta}$ (complex conjugation). Identify the mapping torus $T_f$ and compute its homology.",
        "hints": [
            r"The mapping torus $T_f = (S^1 \times [0,1]) / ((x,1) \sim (f(x), 0))$.",
            r"Check that identifying $(e^{i\theta}, 1) \sim (e^{-i\theta}, 0)$ creates a non-orientable surface.",
            r"Compare the attaching word with that of the Klein bottle.",
        ],
        "solution": {
            "answer": r"$T_f$ is homeomorphic to the Klein bottle $K$. So $H_0 \cong \mathbb{Z}$, $H_1 \cong \mathbb{Z} \oplus \mathbb{Z}/2$, $H_n = 0$ for $n \geq 2$.",
            "steps": [
                r"$T_f = S^1 \times [0,1]/(e^{i\theta},1) \sim (e^{-i\theta}, 0)$. The cylinder is glued at its two boundary circles, but with a reflection, producing a non-orientable surface.",
                r"In terms of the square $[0,1]^2$ model: identify top and bottom edges in the same direction (forming a cylinder) and then identify left and right edges in opposite directions. This is precisely the Klein bottle.",
                r"Formally: in the polygonal model, the attaching word becomes $aba^{-1}b^{-1}$... actually $abab^{-1}$ for the Klein bottle depending on convention. Either way, $T_f \cong K$.",
                r"Homology: $H_0(K) = \mathbb{Z}$, $H_1(K) = \mathbb{Z} \oplus \mathbb{Z}/2$, $H_n(K) = 0$ for $n \geq 2$.",
                r"The free generator of $H_1$ corresponds to the base circle of the fibration, the $\mathbb{Z}/2$ generator corresponds to a fibre circle traversed twice.",
            ],
        },
    },
    # ─── HARD ────────────────────────────────────────────────────────────────
    {
        "id": 29,
        "title": "Cohomology Ring of $\\mathbb{C}P^n$",
        "type": "cohomology",
        "difficulty": "hard",
        "tags": ["cup product", "cohomology ring", "projective spaces"],
        "statement": r"Compute the cohomology ring $H^*(\mathbb{C}P^n;\,\mathbb{Z})$ as a graded ring, including the cup product structure.",
        "hints": [
            r"Additively: $H^{2k}(\mathbb{C}P^n) = \mathbb{Z}$ for $0 \leq k \leq n$, all other groups zero (same as homology by Universal Coefficients).",
            r"Let $\alpha \in H^2(\mathbb{C}P^n)$ be a generator. Compute $\alpha^k = \alpha \cup \cdots \cup \alpha$ ($k$ times).",
            r"Use the fact that $\mathbb{C}P^n$ can be given a CW structure where cells are indexed by $\mathbb{C}^k \subset \mathbb{C}^{n+1}$, and the cup product can be computed via Poincaré duality or by working with a cellular cochain model.",
        ],
        "solution": {
            "answer": r"$H^*(\mathbb{C}P^n;\,\mathbb{Z}) \cong \mathbb{Z}[\alpha]\,/\,(\alpha^{n+1}),\quad |\alpha| = 2.$",
            "steps": [
                r"By the Universal Coefficient Theorem and our computation of $H_*(\mathbb{C}P^n)$: $H^{2k}(\mathbb{C}P^n) \cong \mathbb{Z}$ for $0 \leq k \leq n$, all other cohomology groups zero.",
                r"Let $\alpha \in H^2(\mathbb{C}P^n;\,\mathbb{Z})$ be a generator (the first Chern class of the tautological line bundle).",
                r"The cup product $\alpha^k \in H^{2k}(\mathbb{C}P^n)$ is a generator for each $0 \leq k \leq n$: this follows from the Leray–Hirsch theorem applied to the fibration $\mathbb{C}P^{n-1} \hookrightarrow \mathbb{C}P^n$, or from the fact that $H^*(\mathbb{C}P^n)$ is generated as a ring by $\alpha$.",
                r"$\alpha^{n+1} = 0$ since $H^{2(n+1)}(\mathbb{C}P^n) = 0$ (the complex dimension of $\mathbb{C}P^n$ is $n$).",
                r"No further relations: $\{1, \alpha, \alpha^2, \ldots, \alpha^n\}$ freely generate $H^*(\mathbb{C}P^n)$ as a $\mathbb{Z}$-module.",
                r"Hence $H^*(\mathbb{C}P^n;\,\mathbb{Z}) \cong \mathbb{Z}[\alpha]/(\alpha^{n+1})$, a truncated polynomial ring on a single degree-2 generator.",
            ],
        },
    },
    {
        "id": 30,
        "title": "Cohomology Ring of $T^2$",
        "type": "cohomology",
        "difficulty": "hard",
        "tags": ["cup product", "cohomology ring", "torus", "exterior algebra"],
        "statement": r"Compute the cohomology ring $H^*(T^2;\,\mathbb{Z})$ with the cup product.",
        "hints": [
            r"$H^0 \cong \mathbb{Z}$, $H^1 \cong \mathbb{Z}^2$, $H^2 \cong \mathbb{Z}$ (by Universal Coefficients, since all $H_*$ are free).",
            r"Let $a, b \in H^1(T^2)$ be the generators dual to the two $S^1$ factors. Compute $a \cup a$, $b \cup b$, and $a \cup b$.",
            r"Use the fact that the cup product on $H^1$ satisfies graded commutativity: $a \cup b = -b \cup a$ for odd-degree classes.",
        ],
        "solution": {
            "answer": r"$H^*(T^2;\,\mathbb{Z}) \cong \Lambda_{\mathbb{Z}}[a,b] = \mathbb{Z}\langle 1, a, b, a \cup b\rangle,\quad |a| = |b| = 1,\quad a^2 = b^2 = 0,\quad a \cup b = -b \cup a.$",
            "steps": [
                r"Additively: $H^0 = \mathbb{Z}$, $H^1 = \mathbb{Z}^2$ (with generators $a, b$ dual to $[S^1 \times \{*\}]$ and $[\{*\} \times S^1]$), $H^2 = \mathbb{Z}$.",
                r"Graded commutativity of cup product: $\alpha \cup \beta = (-1)^{pq}\, \beta \cup \alpha$ for $\alpha \in H^p$, $\beta \in H^q$. For $p = q = 1$: $a \cup b = -b \cup a$.",
                r"$a \cup a \in H^2$: since $a \cup a = (-1)^{1\cdot 1}a \cup a = -a \cup a$, we get $2(a \cup a) = 0$. Over $\mathbb{Z}$ (which is torsion-free), $a \cup a = 0$. Similarly $b \cup b = 0$.",
                r"$a \cup b$: This is the fundamental class $[T^2]^* \in H^2(T^2)$ (up to sign), a generator of $H^2 = \mathbb{Z}$. It is non-zero.",
                r"The ring structure is therefore that of an exterior algebra: $H^*(T^2) \cong \Lambda_\mathbb{Z}[a, b]$, with $\mathbb{Z}$-basis $\{1, a, b, a \cup b\}$.",
                r"More generally, $H^*(T^n;\,\mathbb{Z}) \cong \Lambda_\mathbb{Z}[a_1, \ldots, a_n]$, the exterior algebra on $n$ generators of degree 1.",
            ],
        },
    },
    {
        "id": 31,
        "title": "Cohomology Ring of $\\mathbb{R}P^n$ with $\\mathbb{Z}/2$ Coefficients",
        "type": "cohomology",
        "difficulty": "hard",
        "tags": ["cup product", "cohomology ring", "projective spaces", "mod-2 coefficients"],
        "statement": r"Compute the cohomology ring $H^*(\mathbb{R}P^n;\,\mathbb{Z}/2)$ as a graded $\mathbb{Z}/2$-algebra.",
        "hints": [
            r"With $\mathbb{Z}/2$ coefficients, $H^k(\mathbb{R}P^n;\,\mathbb{Z}/2) \cong \mathbb{Z}/2$ for $0 \leq k \leq n$ (by UCT: all torsion is $\mathbb{Z}/2$, so $\operatorname{Ext}^1(\mathbb{Z}/2, \mathbb{Z}/2) \cong \mathbb{Z}/2$ contributes in each odd degree).",
            r"Let $\alpha \in H^1(\mathbb{R}P^n;\,\mathbb{Z}/2)$ be the generator. Over $\mathbb{Z}/2$, graded commutativity gives $\alpha \cup \alpha = \alpha^2$, which need not be zero.",
        ],
        "solution": {
            "answer": r"$H^*(\mathbb{R}P^n;\,\mathbb{Z}/2) \cong (\mathbb{Z}/2)[\alpha]\,/\,(\alpha^{n+1}),\quad |\alpha| = 1.$",
            "steps": [
                r"By the Universal Coefficient Theorem with $\mathbb{Z}/2$ coefficients: $H^k(\mathbb{R}P^n;\,\mathbb{Z}/2) \cong \mathbb{Z}/2$ for all $0 \leq k \leq n$.",
                r"Let $\alpha \in H^1(\mathbb{R}P^n;\,\mathbb{Z}/2) \cong \mathbb{Z}/2$ be the unique non-zero element (Stiefel–Whitney class $w_1$ of the tautological bundle).",
                r"Over $\mathbb{Z}/2$, graded commutativity $\alpha^2 = (-1)^{1\cdot 1}\alpha^2 = -\alpha^2 = \alpha^2$ is trivially satisfied, so $\alpha^2$ is not forced to be zero.",
                r"One computes (e.g.\ via cellular cochains or the Leray–Hirsch theorem) that $\alpha^k \in H^k(\mathbb{R}P^n;\,\mathbb{Z}/2)$ is the unique nonzero element for each $0 \leq k \leq n$.",
                r"$\alpha^{n+1} = 0$ since $H^{n+1}(\mathbb{R}P^n;\,\mathbb{Z}/2) = 0$.",
                r"Conclusion: $H^*(\mathbb{R}P^n;\,\mathbb{Z}/2) \cong (\mathbb{Z}/2)[\alpha]/(\alpha^{n+1})$. For $n = \infty$: $H^*(\mathbb{R}P^\infty;\,\mathbb{Z}/2) \cong (\mathbb{Z}/2)[\alpha]$.",
            ],
        },
    },
    {
        "id": 32,
        "title": "Homology of Lens Spaces $L(p,q)$",
        "type": "homology",
        "difficulty": "hard",
        "tags": ["lens spaces", "CW complex", "torsion", "3-manifolds"],
        "statement": r"Let $p \geq 2$ and $\gcd(p, q) = 1$. Compute $H_n(L(p,q);\,\mathbb{Z})$ for all $n \geq 0$, where $L(p,q)$ is the three-dimensional lens space.",
        "hints": [
            r"$L(p,q)$ is the quotient of $S^3 \subset \mathbb{C}^2$ by the free $\mathbb{Z}/p$-action $(z_1, z_2) \mapsto (e^{2\pi i/p} z_1,\, e^{2\pi iq/p} z_2)$.",
            r"$L(p,q)$ admits a CW structure with one cell in each of dimensions $0, 1, 2, 3$.",
            r"The cellular chain complex is $0 \to \mathbb{Z} \xrightarrow{0} \mathbb{Z} \xrightarrow{p} \mathbb{Z} \xrightarrow{0} \mathbb{Z} \to 0$ (independent of $q$ for homology with $\mathbb{Z}$ coefficients).",
        ],
        "solution": {
            "answer": r"$H_0(L(p,q)) \cong \mathbb{Z},\quad H_1(L(p,q)) \cong \mathbb{Z}/p,\quad H_2(L(p,q)) = 0,\quad H_3(L(p,q)) \cong \mathbb{Z}.$",
            "steps": [
                r"$L(p,q)$ is a closed orientable 3-manifold, so $H_3 = \mathbb{Z}$ (fundamental class) and $H_0 = \mathbb{Z}$ (connected).",
                r"The CW structure has one cell in each dimension $0, 1, 2, 3$. The boundary maps are: $d_1 = 0$ (the 1-cell is a loop generating $\pi_1 = \mathbb{Z}/p$), $d_2 = \times p$, $d_3 = 0$.",
                r"Chain complex: $0 \to \mathbb{Z} \xrightarrow{0} \mathbb{Z} \xrightarrow{\times p} \mathbb{Z} \xrightarrow{0} \mathbb{Z} \to 0$.",
                r"$H_3 = \ker(0)/0 = \mathbb{Z}$; $H_2 = \ker(\times p)/\operatorname{im}(0) = 0$; $H_1 = \ker(0)/\operatorname{im}(\times p) = \mathbb{Z}/p$.",
                r"Note: $H_*(L(p,q))$ depends only on $p$, not on $q$. To distinguish $L(p,q)$ from $L(p,q')$ one needs finer invariants (linking form, Reidemeister torsion).",
                r"Example: $L(2,1) \cong \mathbb{R}P^3$. Indeed $H_*(L(2,1)) = (\mathbb{Z}, \mathbb{Z}/2, 0, \mathbb{Z}) = H_*(\mathbb{R}P^3)$. ✓",
            ],
        },
    },
    {
        "id": 33,
        "title": "Are $L(7,1)$ and $L(7,2)$ Homeomorphic?",
        "type": "homeomorphism",
        "difficulty": "hard",
        "tags": ["lens spaces", "Reidemeister torsion", "linking form", "3-manifolds"],
        "statement": r"Show that $L(7,1)$ and $L(7,2)$ have identical integral homology groups, yet are not homeomorphic.",
        "hints": [
            r"Both have $H_0 = \mathbb{Z}$, $H_1 = \mathbb{Z}/7$, $H_2 = 0$, $H_3 = \mathbb{Z}$. The homology alone cannot distinguish them.",
            r"The linking form $\lambda: H_1 \times H_1 \to \mathbb{Q}/\mathbb{Z}$ is a homeomorphism invariant. For $L(p,q)$, it satisfies $\lambda([\gamma], [\gamma]) = q/p \pmod{\mathbb{Z}}$.",
            r"Two lens spaces $L(p,q)$ and $L(p,q')$ are homeomorphic if and only if $q' \equiv \pm q^{\pm 1} \pmod{p}$.",
        ],
        "solution": {
            "answer": r"$L(7,1)$ and $L(7,2)$ have the same homology but are not homeomorphic: $2 \not\equiv \pm 1^{\pm 1} \pmod 7$.",
            "steps": [
                r"Both spaces have $H_*(L(7,q)) = (\mathbb{Z}, \mathbb{Z}/7, 0, \mathbb{Z})$ for $q = 1, 2$. Integral homology cannot distinguish them.",
                r"The linking form: for the generator $[\gamma]$ of $H_1(L(p,q)) = \mathbb{Z}/p$, the linking form satisfies $\lambda([\gamma],[\gamma]) = q/p \in \mathbb{Q}/\mathbb{Z}$.",
                r"For $L(7,1)$: $\lambda([\gamma],[\gamma]) = 1/7$. For $L(7,2)$: $\lambda([\gamma],[\gamma]) = 2/7$.",
                r"An isometry of linking forms preserving orientation requires $1/7 \equiv \pm(n^2 \cdot 2/7) \pmod{1}$ for some integer $n$, i.e.\ $1 \equiv \pm 2n^2 \pmod{7}$. Checking: $2n^2 \pmod{7}$ takes values $\{0,2,1,4\}$ for $n=0,1,2,3$; neither $+1$ nor $-1 \equiv 6$ appear as $2n^2$.",
                r"The homeomorphism criterion: $L(p,q) \cong L(p,q')$ iff $q' \equiv \pm q^{\pm 1} \pmod p$. For $(p,q)=(7,1)$ and $q'=2$: $\pm 1^{\pm 1} \equiv \pm 1 \equiv 1$ or $6 \pmod 7$. Since $2 \neq 1, 6$, the spaces are not homeomorphic.",
                r"This is the classical example showing homology is insufficient to classify lens spaces; one needs Reidemeister torsion or the linking form.",
            ],
        },
    },
    {
        "id": 34,
        "title": "Homology of $\\mathbb{R}P^\\infty$",
        "type": "homology",
        "difficulty": "hard",
        "tags": ["infinite CW complexes", "classifying spaces", "Eilenberg-MacLane"],
        "statement": r"Compute $H_n(\mathbb{R}P^\infty;\,\mathbb{Z})$ for all $n \geq 0$, where $\mathbb{R}P^\infty = \varinjlim \mathbb{R}P^n$ is the infinite real projective space.",
        "hints": [
            r"$\mathbb{R}P^\infty$ is the classifying space $B(\mathbb{Z}/2) = K(\mathbb{Z}/2, 1)$: its only non-trivial homotopy group is $\pi_1 = \mathbb{Z}/2$.",
            r"Use the CW structure inherited from $\mathbb{R}P^n$: one cell in each dimension $0, 1, 2, \ldots$",
            r"The boundary maps alternate $d_k = 0$ (k odd), $d_k = \times 2$ (k even), continuing forever.",
        ],
        "solution": {
            "answer": r"$H_0(\mathbb{R}P^\infty) \cong \mathbb{Z}$;\quad $H_k(\mathbb{R}P^\infty) \cong \mathbb{Z}/2$ for $k$ odd, $k \geq 1$;\quad $H_k(\mathbb{R}P^\infty) = 0$ for $k$ even, $k \geq 2$.",
            "steps": [
                r"The CW structure on $\mathbb{R}P^\infty$ has one cell in every dimension $\geq 0$. Chain complex (each $C_k = \mathbb{Z}$): $\cdots \xrightarrow{0} \mathbb{Z} \xrightarrow{\times 2} \mathbb{Z} \xrightarrow{0} \mathbb{Z} \xrightarrow{\times 2} \mathbb{Z} \xrightarrow{0} \mathbb{Z} \to 0$.",
                r"For even $k \geq 2$: $d_k = \times 2$ and $d_{k+1} = 0$. $H_k = \ker(\times 2)/\operatorname{im}(0) = 0$.",
                r"For odd $k \geq 1$: $d_k = 0$ and $d_{k+1} = \times 2$. $H_k = \ker(0)/\operatorname{im}(\times 2) = \mathbb{Z}/2$.",
                r"$H_0 = \mathbb{Z}$ (one connected component, since every $\mathbb{R}P^n$ is connected).",
                r"Note the key difference from the finite case $\mathbb{R}P^{2m}$: there is no top cell to give a $\mathbb{Z}$ in top homology; the pattern $\mathbb{Z}/2$ in all odd degrees continues indefinitely.",
            ],
        },
    },
    {
        "id": 35,
        "title": "Homology of $\\mathbb{C}P^\\infty$",
        "type": "homology",
        "difficulty": "hard",
        "tags": ["infinite CW complexes", "classifying spaces", "Eilenberg-MacLane"],
        "statement": r"Compute $H_n(\mathbb{C}P^\infty;\,\mathbb{Z})$ for all $n \geq 0$, where $\mathbb{C}P^\infty = \varinjlim \mathbb{C}P^n$ is the infinite complex projective space.",
        "hints": [
            r"$\mathbb{C}P^\infty$ is the classifying space $BU(1) = K(\mathbb{Z}, 2)$: its only non-trivial homotopy group is $\pi_2 = \mathbb{Z}$.",
            r"The CW structure has one cell in each even dimension $0, 2, 4, \ldots$ and no odd-dimensional cells.",
        ],
        "solution": {
            "answer": r"$H_{2k}(\mathbb{C}P^\infty;\,\mathbb{Z}) \cong \mathbb{Z}$ for all $k \geq 0$;\quad $H_n(\mathbb{C}P^\infty) = 0$ for $n$ odd.",
            "steps": [
                r"CW structure: one cell $e^{2k}$ in each even dimension $2k$, $k \geq 0$. All odd cells absent.",
                r"Chain complex: $C_{2k} = \mathbb{Z}$, $C_{\text{odd}} = 0$. All boundary maps are zero (since $C_{2k-1} = 0$).",
                r"$H_{2k} = \ker(d_{2k})/\operatorname{im}(d_{2k+1}) = \mathbb{Z}/0 = \mathbb{Z}$ for all $k \geq 0$.",
                r"$H_{\text{odd}} = 0$ since $C_{\text{odd}} = 0$.",
                r"This is the cohomology of the Eilenberg–MacLane space $K(\mathbb{Z},2)$; by contrast, $H^*(\mathbb{C}P^\infty;\mathbb{Z}) \cong \mathbb{Z}[\alpha]$ (a polynomial ring, not truncated), where $|\alpha| = 2$.",
            ],
        },
    },
    {
        "id": 36,
        "title": "Cohomology Ring of $S^n \\times S^n$",
        "type": "cohomology",
        "difficulty": "hard",
        "tags": ["cup product", "cohomology ring", "product spaces"],
        "statement": r"Compute the cohomology ring $H^*(S^n \times S^n;\,\mathbb{Z})$ for $n \geq 1$, including the cup product structure.",
        "hints": [
            r"$H^k(S^n \times S^n) \cong \mathbb{Z}$ for $k = 0, n, n, 2n$ (with $H^n = \mathbb{Z}^2$ when we count both factors), by Künneth.",
            r"Let $a \in H^n(S^n \times \{*\})$ and $b \in H^n(\{*\} \times S^n)$ be generators pulled back to $H^n(S^n \times S^n)$. Determine $a \cup a$, $b \cup b$, $a \cup b$.",
            r"For $n$ odd, $a \cup a = 0$ (graded commutativity). What happens for $n$ even?",
        ],
        "solution": {
            "answer": r"$H^*(S^n \times S^n;\,\mathbb{Z}) \cong \mathbb{Z}[a,b]\,/\,(a^2,\, b^2,\, ab - (-1)^n ba)$ with $|a| = |b| = n$. In particular $a \cup b$ generates $H^{2n} \cong \mathbb{Z}$.",
            "steps": [
                r"By Künneth: $H^0 = \mathbb{Z}$, $H^n = \mathbb{Z}^2$ (with generators $a = p_1^*([\text{fund.\ class}])$ and $b = p_2^*([\text{fund.\ class}])$), $H^{2n} = \mathbb{Z}$.",
                r"For $a \cup a \in H^{2n}$: by graded commutativity, $a \cup a = (-1)^{n \cdot n} a \cup a = (-1)^{n^2} a \cup a$. If $n$ is odd, $(-1)^{n^2} = -1$, so $2(a \cup a) = 0$, giving $a \cup a = 0$ over $\mathbb{Z}$. If $n$ is even, no constraint from commutativity alone.",
                r"For $n$ even: $a \cup a$ lives in $H^{2n}(S^n \times S^n) \cong \mathbb{Z}$, but $a$ pulls back from a factor $S^n$ with $H^{2n}(S^n) = 0$, so $a \cup a = 0$ regardless.",
                r"For $a \cup b$: $a$ and $b$ come from different factors. By the Künneth formula for cohomology, $a \cup b = p_1^*([S^n]) \cup p_2^*([S^n])$ is the fundamental class of $S^n \times S^n$, a generator of $H^{2n} = \mathbb{Z}$. Hence $a \cup b \neq 0$.",
                r"The graded commutativity relation: $a \cup b = (-1)^{n \cdot n} b \cup a = (-1)^{n^2} b \cup a$.",
                r"Summary: $H^* = \mathbb{Z}\langle 1, a, b, a\cup b\rangle$ with $a^2 = b^2 = 0$ and $a \cup b = \pm b \cup a$ (exterior-algebra-like for $n$ odd, commutative for $n$ even).",
            ],
        },
    },
    {
        "id": 37,
        "title": "Are $\\mathbb{C}P^2$ and $S^4$ Homeomorphic?",
        "type": "homeomorphism",
        "difficulty": "hard",
        "tags": ["homeomorphism invariants", "4-manifolds", "cup product"],
        "statement": r"Show that $\mathbb{C}P^2$ and $S^4$ are not homeomorphic, using both homology and the cup product structure.",
        "hints": [
            r"Compare $H_2(\mathbb{C}P^2)$ and $H_2(S^4)$.",
            r"As a stronger invariant, compare the cup product maps $H^2 \otimes H^2 \to H^4$ for the two spaces.",
        ],
        "solution": {
            "answer": r"No, $\mathbb{C}P^2 \not\cong S^4$. They differ already in $H_2$.",
            "steps": [
                r"$H_2(\mathbb{C}P^2) \cong \mathbb{Z}$ while $H_2(S^4) = 0$. A homeomorphism would require these to be isomorphic.",
                r"Since $\mathbb{Z} \neq 0$, no homeomorphism exists. The proof is complete.",
                r"For additional insight: the cup product $\alpha \cup \alpha \in H^4(\mathbb{C}P^2) \cong \mathbb{Z}$ is a generator (since $H^*(\mathbb{C}P^2) = \mathbb{Z}[\alpha]/(\alpha^3)$). So the cup product pairing on $H^2(\mathbb{C}P^2)$ is non-degenerate.",
                r"For $S^4$: $H^2(S^4) = 0$, so there is no non-trivial cup product at all.",
                r"The intersection form (on $H_2$) is a fundamental invariant of 4-manifolds. $\mathbb{C}P^2$ has intersection form $\langle 1 \rangle$; $S^4$ has the zero form (rank 0). Donaldson's theorem, Freedman's classification, and Seiberg–Witten theory are all built on such distinctions.",
            ],
        },
    },
    {
        "id": 38,
        "title": "Homology of the $K3$ Surface",
        "type": "homology",
        "difficulty": "hard",
        "tags": ["4-manifolds", "complex surfaces", "Hodge theory"],
        "statement": r"Compute $H_n(K3;\,\mathbb{Z})$ for the $K3$ surface, a compact complex surface with trivial canonical bundle and $b_1 = 0$.",
        "hints": [
            r"Use the fact that $K3$ is a simply-connected compact Kähler surface with $\chi(K3) = 24$.",
            r"By Poincaré duality and the Hodge decomposition: $b_0 = b_4 = 1$, $b_1 = b_3 = 0$, and $b_2 = \chi - b_0 - b_4 = 22$.",
            r"$\pi_1(K3) = 1$ (simply connected), so $H_1(K3;\mathbb{Z}) = 0$ and by the universal coefficient theorem there is no torsion in $H_2$.",
        ],
        "solution": {
            "answer": r"$H_0(K3) \cong \mathbb{Z},\quad H_1(K3) = 0,\quad H_2(K3) \cong \mathbb{Z}^{22},\quad H_3(K3) = 0,\quad H_4(K3) \cong \mathbb{Z}.$",
            "steps": [
                r"$K3$ is a simply-connected compact complex surface; the Euler characteristic is $\chi(K3) = 24$ (a consequence of $c_2(K3) = 24$, i.e.\ the second Chern class integrates to 24).",
                r"Hodge numbers: $h^{0,0} = h^{2,2} = 1$, $h^{1,0} = h^{0,1} = 0$ (since $b_1 = 0$), $h^{2,0} = h^{0,2} = 1$, $h^{1,1} = 20$. So $b_2 = h^{2,0} + h^{1,1} + h^{0,2} = 1 + 20 + 1 = 22$.",
                r"Betti numbers: $b_0 = 1, b_1 = 0, b_2 = 22, b_3 = 0, b_4 = 1$. (Check: $1 - 0 + 22 - 0 + 1 = 24 = \chi$. ✓)",
                r"Since $\pi_1(K3) = 1$, $H_1 = 0$. By UCT: $H_2 = \mathbb{Z}^{22}$ (no torsion, since $H_1 = 0$ contributes no Ext).",
                r"By Poincaré duality: $H_k(K3) \cong H^{4-k}(K3) \cong H_{4-k}(K3)$. So $H_3 \cong H_1 = 0$.",
                r"The intersection form on $H_2(K3;\mathbb{Z}) \cong \mathbb{Z}^{22}$ is $E_8 \oplus E_8 \oplus H \oplus H \oplus H$ (three hyperbolic planes and two $E_8$ lattices). This is a deep result.",
            ],
        },
    },
    {
        "id": 39,
        "title": "Euler Characteristic and Homology",
        "type": "homology",
        "difficulty": "hard",
        "tags": ["Euler characteristic", "Betti numbers", "CW complexes"],
        "statement": r"Prove that for a finite CW complex $X$, the Euler characteristic satisfies $\chi(X) = \sum_{n \geq 0} (-1)^n \operatorname{rank}(H_n(X;\mathbb{Z}))$ (the Betti number formula), where $\operatorname{rank}$ denotes the free rank.",
        "hints": [
            r"Let $c_n$ denote the number of $n$-cells and $\beta_n = \operatorname{rank}(H_n)$ (Betti numbers). We want to show $\sum (-1)^n c_n = \sum (-1)^n \beta_n$.",
            r"Write $c_n = \operatorname{rank}(\ker d_n) + \operatorname{rank}(\operatorname{im} d_n)$ and $\beta_n = \operatorname{rank}(\ker d_n) - \operatorname{rank}(\operatorname{im} d_{n+1})$.",
            r"Perform a telescoping sum.",
        ],
        "solution": {
            "answer": r"$\chi(X) = \sum_{n} (-1)^n c_n = \sum_{n} (-1)^n \beta_n,$ where $\beta_n = \operatorname{rank} H_n(X;\mathbb{Z})$.",
            "steps": [
                r"Define $Z_n = \ker d_n \subseteq C_n$ and $B_n = \operatorname{im} d_{n+1} \subseteq C_n$. We have $H_n = Z_n/B_n$, so $\beta_n = \operatorname{rank} Z_n - \operatorname{rank} B_n$.",
                r"Also, $\operatorname{rank} C_n = c_n = \operatorname{rank} Z_n + \operatorname{rank}(\operatorname{im} d_n) = \operatorname{rank} Z_n + \operatorname{rank} B_{n-1}$.",
                r"So $(-1)^n c_n = (-1)^n \operatorname{rank} Z_n + (-1)^n \operatorname{rank} B_{n-1}$.",
                r"Summing over all $n$: $\sum_n (-1)^n c_n = \sum_n (-1)^n \operatorname{rank} Z_n + \sum_n (-1)^n \operatorname{rank} B_{n-1}$.",
                r"Re-index the second sum: $\sum_n (-1)^n \operatorname{rank} B_{n-1} = \sum_n (-1)^{n+1} \operatorname{rank} B_n$.",
                r"Hence $\sum (-1)^n c_n = \sum (-1)^n (\operatorname{rank} Z_n - \operatorname{rank} B_n) = \sum (-1)^n \beta_n$. QED.",
            ],
        },
    },
    {
        "id": 40,
        "title": "Poincaré Duality for Closed Orientable Manifolds",
        "type": "cohomology",
        "difficulty": "hard",
        "tags": ["Poincaré duality", "manifolds", "orientation"],
        "statement": r"State Poincaré duality for closed orientable $n$-manifolds and verify it for $\Sigma_g$ (genus $g$ orientable surface) and $\mathbb{C}P^2$.",
        "hints": [
            r"Poincaré duality: for a closed orientable $n$-manifold $M$, cap product with the fundamental class $[M] \in H_n(M;\mathbb{Z})$ gives an isomorphism $H^k(M;\mathbb{Z}) \xrightarrow{\cong} H_{n-k}(M;\mathbb{Z})$.",
            r"Use this to verify $H^k \cong H_{n-k}$ for the two examples.",
        ],
        "solution": {
            "answer": r"Poincaré duality: $H^k(M;\mathbb{Z}) \cong H_{n-k}(M;\mathbb{Z})$ for closed orientable $n$-manifolds $M$.",
            "steps": [
                r"Theorem (Poincaré duality): If $M$ is a compact orientable $n$-manifold without boundary with fundamental class $[M]$, then $-\cap [M]: H^k(M;\mathbb{Z}) \to H_{n-k}(M;\mathbb{Z})$ is an isomorphism for all $k$.",
                r"Verification for $\Sigma_g$ ($n=2$): $H^0 \cong H_2 = \mathbb{Z}$, $H^1 \cong H_1 = \mathbb{Z}^{2g}$, $H^2 \cong H_0 = \mathbb{Z}$. All match. ✓",
                r"(Using UCT: $H^k(\Sigma_g;\mathbb{Z}) \cong H_k(\Sigma_g;\mathbb{Z})$ since all $H_k(\Sigma_g)$ are free.)",
                r"Verification for $\mathbb{C}P^2$ ($n=4$): $H^0 \cong H_4 = \mathbb{Z}$, $H^2 \cong H_2 = \mathbb{Z}$, $H^4 \cong H_0 = \mathbb{Z}$. ✓",
                r"Implication: $\beta_k(M) = \beta_{n-k}(M)$ (Betti numbers are symmetric). For $\Sigma_g$: $(\beta_0, \beta_1, \beta_2) = (1, 2g, 1)$, symmetric around $k = 1$. ✓",
                r"For non-orientable manifolds (or manifolds with boundary), duality holds with twisted coefficients or relative cohomology.",
            ],
        },
    },
    {
        "id": 41,
        "title": "Homology of the Configuration Space $F(\\mathbb{R}^2, 2)$",
        "type": "homology",
        "difficulty": "hard",
        "tags": ["configuration spaces", "deformation retract", "braid groups"],
        "statement": r"The configuration space of 2 distinct ordered points in $\mathbb{R}^2$ is $F(\mathbb{R}^2, 2) = \{(x_1, x_2) \in (\mathbb{R}^2)^2 : x_1 \neq x_2\}$. Identify its homotopy type and compute $H_n(F(\mathbb{R}^2,2);\,\mathbb{Z})$.",
        "hints": [
            r"The map $(x_1, x_2) \mapsto x_2 - x_1$ sends $F(\mathbb{R}^2,2)$ to $\mathbb{R}^2 \setminus \{0\}$.",
            r"Consider the fibration: fix $x_1 = 0$ (passing to the quotient by translation) to see $F(\mathbb{R}^2,2) \simeq \mathbb{R}^2 \setminus \{0\} \simeq S^1$.",
        ],
        "solution": {
            "answer": r"$F(\mathbb{R}^2,2) \simeq S^1$, so $H_0 \cong \mathbb{Z}$, $H_1 \cong \mathbb{Z}$, $H_n = 0$ for $n \geq 2$.",
            "steps": [
                r"$F(\mathbb{R}^2,2)$ is the complement of the diagonal $\Delta = \{(x,x)\}$ in $(\mathbb{R}^2)^2 \cong \mathbb{R}^4$.",
                r"The map $\phi: F(\mathbb{R}^2,2) \to \mathbb{R}^2 \setminus \{0\}$ given by $\phi(x_1,x_2) = x_2 - x_1$ is a homotopy equivalence. (It admits a fibre-wise deformation retraction via translation.)",
                r"$\mathbb{R}^2 \setminus \{0\} \simeq S^1$ (via radial deformation retraction $x \mapsto x/\|x\|$).",
                r"Therefore $F(\mathbb{R}^2,2) \simeq S^1$, giving $H_0 = H_1 = \mathbb{Z}$, $H_n = 0$ for $n \geq 2$.",
                r"The generator of $\pi_1 = H_1 = \mathbb{Z}$ is the loop where one point winds around the other: the pure braid group $P_2 = \pi_1(F(\mathbb{R}^2,2)) = \mathbb{Z}$.",
                r"More generally: $F(\mathbb{R}^2, n) \simeq \bigvee_{k=1}^{n-1} \bigvee^k S^1$ (homotopy equivalent to a wedge of circles), and $H_1(F(\mathbb{R}^2,n)) = \mathbb{Z}^{n(n-1)/2}$.",
            ],
        },
    },
    {
        "id": 42,
        "title": "Cohomology of $\\mathbb{C}P^2 \\# \\mathbb{C}P^2$ (Connected Sum)",
        "type": "cohomology",
        "difficulty": "hard",
        "tags": ["connected sum", "4-manifolds", "cup product", "Mayer-Vietoris"],
        "statement": r"Compute $H_*(\mathbb{C}P^2 \# \mathbb{C}P^2;\,\mathbb{Z})$ and describe the cup product structure on $H^*(\mathbb{C}P^2 \# \mathbb{C}P^2;\,\mathbb{Z})$.",
        "hints": [
            r"For the connected sum of two $n$-manifolds, $M \# N = (M \setminus D^n) \cup_{S^{n-1}} (N \setminus D^n)$. Apply Mayer–Vietoris.",
            r"$M \setminus D^n$ has $H_n = 0$ (the $n$-cycle is killed by removing a disk). Its homology coincides with $M$'s except in degree $n$.",
            r"The cup product in the connected sum is determined by the cup products in each summand; for classes from different summands the cup product vanishes.",
        ],
        "solution": {
            "answer": r"$H_0 \cong H_4 \cong \mathbb{Z}$;\quad $H_2 \cong \mathbb{Z}^2$;\quad $H_1 = H_3 = 0$. Cup product: $a_1^2 = a_2^2 = [\text{pt}]$, $a_1 \cup a_2 = 0$, where $a_1, a_2$ are generators of each $H^2(\mathbb{C}P^2)$.",
            "steps": [
                r"Write $X = \mathbb{C}P^2 \# \mathbb{C}P^2 = U \cup V$ where $U = \mathbb{C}P^2 \setminus \{D^4\}$, $V = \mathbb{C}P^2 \setminus \{D^4\}$, and $U \cap V \simeq S^3$.",
                r"$H_k(\mathbb{C}P^2 \setminus D^4)$: removing an open disk kills $H_4$ and $H_3$ but preserves $H_0 = \mathbb{Z}$, $H_2 = \mathbb{Z}$. (Use the long exact sequence of the pair $(\mathbb{C}P^2, D^4)$.)",
                r"Mayer–Vietoris for $X = U \cup V$, $U \cap V \simeq S^3$: in degrees 2 and below, the sequence gives $H_2(X) = H_2(U) \oplus H_2(V) = \mathbb{Z}^2$.",
                r"Since $H_1(U) = H_1(V) = H_1(S^3) = 0$, we get $H_1(X) = 0$. Similarly $H_3(X) = 0$. $H_4(X) = \mathbb{Z}$ (orientable closed 4-manifold).",
                r"Cup product: Let $a_1, a_2 \in H^2(X)$ be the generators (pulled back from each $\mathbb{C}P^2$ factor). Since $a_i$ is supported on $U$ (or $V$) and $a_j$ on $V$ (or $U$), and $U \cap V = S^3$ has $H^2 = 0$, we get $a_1 \cup a_2 = 0$.",
                r"But $a_i \cup a_i$: this equals the generator of $H^4$ coming from the $i$-th copy of $\mathbb{C}P^2$. The intersection form is $\begin{pmatrix}1 & 0 \\ 0 & 1\end{pmatrix}$, i.e.\ $\langle 1 \rangle \oplus \langle 1 \rangle$. Contrast: $\overline{\mathbb{C}P^2} \# \mathbb{C}P^2$ has form $\langle 1 \rangle \oplus \langle -1 \rangle$.",
            ],
        },
    },
]
